mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.swing.jxc.demo.swing  # 注意：对应实体类的路径
logging:
  level:
    com.swing.jxc.demo.swing:
      debug
